### ISSUE TITLE
AnimatedImage not resizable

### ISSUE THREAD

**Issue by maundytime** [SDWebImage/SDWebImageSwiftUI#3]
AnimatedImage seems not resizable, always stretched.
WebImage aspectRatio() works well.

![](https://img.pawoo.net/media_attachments/files/018/947/242/original/d4be052474790b21.png)

When they are embedded in List, after scrolling out and in, AnimatedImage size would change to its image original size.

![](https://img.pawoo.net/media_attachments/files/018/947/245/original/8dc4208a366e310a.png)

**Comment by dreampiggy** [comment]
This is the Known issue. Since the AnimatedImage is backing UIKit View `SDAnimatedImageView`. The time when I written the first version, there are no any **Public API** in Swift UI, to response for the modifier of View protocol. So the `SDAnimatedImageView` can not set any aspect fit changes.

I'll have a check again if there are new API available. And PR is welcomed if you have knowledge for this.

**Comment by dreampiggy** [comment]
See this line: https://github.com/SDWebImage/SDWebImageSwiftUI/blob/master/Example/SDWebImageSwiftUIDemo/ContentView.swift#L21

**Comment by dreampiggy** [comment]
I've add two `scaleToFit()` and `scaleToFill()` method on AnimatedImage. Maybe this should help with it.

Released [v0.1.1](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.1.1)

**Comment by maundytime** [comment]
Worked when not in a scrolling List. Size still become real image size from the frame size when in list and scrolling. I would give feedback if any solutions found.

**Comment by dreampiggy** [comment]
Can you help to provide your demo, so that we can use that to debug and investigate.

**Comment by maundytime** [comment]
https://github.com/maundytime/Demo
When scrolling the AnimatedImage out of screen and scrolling back, the image size changed to it original image size. It seems the content layer scale to 1x.

**Comment by maundytime** [comment]
I did test with SDWebImage and YYWebImage on new commit, they appear as stretched by default, and both change the content mode when cell re-enter screen, but in different way.

![](https://img.pawoo.net/media_attachments/files/019/306/825/original/2aab8281a728820a.jpeg)

**Comment by dreampiggy** [comment]
Seems Apple's issue of SwiftUI layout engine. There is nothing to triiger inside `SDAnimatedImageView` or `YYAnimatedImageView` both itself.

When scrolling outside, both of them will receive a `setFrame` call from SwiftUI layout engine. But the size is wrong.

Why you look the size different, because `SDAnimatedImageView`, or `SDWebImage`, follows the correct scale factor of your URL. This URL image size is treat as 1x. (480x258). You can always specify a custom scale factor using context option `.imageScaleFactor = 2` for controlling this.

However , YYImage treat it as 2x, which result in (240x129), but this is totally wrong and considered to be a bug. No any information for them to detect like this.  But sadlly YYImage is no longer manitained by anyone...

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/65656309-fb9f3a80-e051-11e9-8793-9c0cd02eead9.png)

**Comment by dreampiggy** [comment]
Maybe this need a workaround, to override the `updateUIView` method in `AnimatedImage` ? And refresh the `UIView.frame` ?

**Comment by dreampiggy** [comment]
@maundytime It seems SwiftUI's `Image` struct has a method `resizable(capInsets:resizingMode:)`. This method will cause the image to be sizable by `.frame` modifier.

If you use `Image` without that resizable, you will face the exact same issue as custom UIViewPresentable.

See my result test:

![image](https://user-images.githubusercontent.com/6919743/65658744-8b95b200-e05b-11e9-8d5b-73b5fdfccb42.png)

![image](https://user-images.githubusercontent.com/6919743/65658752-951f1a00-e05b-11e9-81b9-dc80d9e3740e.png)

**Comment by dreampiggy** [comment]
So, this problem becomes that `How can a UIViewRepresentable implemnts the resizable() method` ? Because the `resizable` is the `Image` method, not the `View` method. :(

![image](https://user-images.githubusercontent.com/6919743/65658813-cd265d00-e05b-11e9-8662-acdcd35ba25d.png)

This need we to do. Maybe you can investigate it as well.

**Comment by maundytime** [comment]
I found a solution to the size broken bug, but not sure if it is hacky. It seems a wrapper avoid SwiftUI call setFrame directly on SDAnimatedImageView when cell reloaded. Hope it will be helpful.

```
public struct AnimatedImage: UIViewRepresentable {
    var url: URL?

    public func makeUIView(context: UIViewRepresentableContext<AnimatedImage>) -> Wrapper {
        let w = Wrapper()
        w.animatedImageView.sd_setImage(with: url)
        return w
    }
    
    public func updateUIView(_ uiView: Wrapper, context: UIViewRepresentableContext<AnimatedImage>) {
        
    }
}

public class Wrapper: UIView {
    let animatedImageView = SDAnimatedImageView()
    
    override init (frame : CGRect) {
        super.init(frame : frame)
        addSubview(animatedImageView)
    }
    
    public override func layoutSubviews() {
        super.layoutSubviews()
        animatedImageView.frame = bounds
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
```

**Comment by dreampiggy** [comment]
@maundytime This is good choice. PR is welcomed.

**Comment by dreampiggy** [comment]
Actually, for normal cases, you can always use `WebImage` to play animation. This works like `UIImageView` animation on SDWebImage. The `AnimatedImage` is the advanced choice to avoid large animation images which consume much more memory.

**Comment by dreampiggy** [comment]
@maundytime See #7, I use the wrapper view to implements the new AnimatedImage. Maybe this can solve the strange behavior from SwiftUI

**Comment by dreampiggy** [comment]
Seems I can close this issue now.

SDWebImageSwiftUI released [0.2.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.2.0), which supports the success/failure/progress event handling. Glad to see if you can have a try ;)

**Comment by cprovatas** [comment]
@dreampiggy Did you file a feedback for this?  I have the same issue as well.

**Comment by dreampiggy** [comment]
See: https://stackoverflow.com/questions/57969470/trouble-to-make-a-custom-uiview-aspect-scale-fit-fill-with-swiftui

**Comment by cprovatas** [comment]
@dreampiggy Thanks.  I have filed a feedback and will let you know if anything comes out of it.
