### ISSUE TITLE
Does not work on tvOS borderless style

### ISSUE THREAD

**Issue by zijiaZ** [SDWebImage/SDWebImageSwiftUI#320]
Based on the doc https://developer.apple.com/documentation/swiftui/primitivebuttonstyle/borderless,
On tvOS, this borderless style has a default hover effect, WebImage does not have it, but AsyncImage does.

**Comment by dreampiggy** [comment]
😂

Using `Button` and `WebImage` has known issue. Because there are some special handing in SwiftUI internal (`Image` is the basic building block actually)

From v3.0.0, you can use the `AsyncImage` like API, which you receive a `WebImagePhase` and you can get a `SwiftUI.Image` to do customization after downloaded, maybe that one helps.

**Comment by dreampiggy** [comment]
Does this helps ? If so you can close this issue.
