### ISSUE TITLE
 image format support SVG

### ISSUE THREAD

**Issue by mkalayci35** [SDWebImage/SDWebImageSwiftUI#50]
Can you add svg support?

**Comment by dreampiggy** [comment]
SDWebImage’s decoding system is plugin based and extensiable.

Here we already have one https://github.com/SDWebImage/SDWebImageSVGCoder

Note this SVG plugin previously need a new UIView subclass `SVGKImageView`. However, it can be applied with iOS 13’s native support via private API CoreSVG.framework

Checkout that SVGCoder’s [https://github.com/SDWebImage/SDWebImageSVGCoder/tree/iOS13_SVG](iOS13_SVG) branch, which can be used with our `AnimatedInage` struct

**Comment by dreampiggy** [comment]
However, seems the best vector format on iOS platform. is the PDF, which Apple have all built-in support. I strongly recommend to create Vector PDF instead. Which is portable and easy to use compared to SVG.

Using https://github.com/SDWebImage/SDWebImagePDFCoder can simply add support to PDF vector without lossing details, you can try to use our demo and run the showcase code.

**Comment by mkalayci35** [comment]
I'm not adding xcode. Dont You have a library for SwiftUI.

**Comment by dreampiggy** [comment]
> I'm not adding xcode. Dont You have a library for SwiftUI.

Emm. I guess you means:

`I can not add SDWebImagePDFCoder/SDWebImageSVGCoder` to Xcode using SwiftPM ? Don't you have a Swift PM library for that ?`

Thoes coder plugins are not supported SwiftPM now. Because some of them, using the upstream dependency does not support SwiftPM (dependnecy is a recusive problem). You can try to use CocoaPods firstly.

But if you want, I can provide a special compatble version which use SwiftPM (those PDF/SVG coder)

**Comment by dreampiggy** [comment]
@mkalayci35 
PDFCoder support SwiftPM: https://github.com/SDWebImage/SDWebImagePDFCoder/releases/tag/0.4.0

**Comment by dreampiggy** [comment]
@mkalayci35 
SVGCoder iOS13_SVG branch support SwiftPM, watchOS, and remove the SVGKit: https://github.com/SDWebImage/SDWebImageSVGCoder/commits/iOS13_SVG

**Comment by dreampiggy** [comment]
So, it's supported. Here is the run demo with some sample SVG/PDFs. Note only `AnimatedImage` is supported, because it use a `UIImageView`, and UIKit support it. (This is Apple's choose). 

`WebImage` and `SwiftUI.Image` does not support PDF/SVG or any vector format, it's harded-code to support Static Image. Send [Radar](https://feedbackassistant.apple.com/welcome) to Apple's SwiftUI team if you want iOS 14 to make it works.

![image](https://user-images.githubusercontent.com/6919743/68606453-7381d100-04e9-11ea-9aa9-e819588cb48b.png)

**Comment by dreampiggy** [comment]
macOS Demo as well:

![image](https://user-images.githubusercontent.com/6919743/68607060-c27c3600-04ea-11ea-89a3-1579952b8096.png)

**Comment by mkalayci35** [comment]
I was wondering how you did wrong when the sample code throws at me. Thank you so much.

**Comment by mkalayci35** [comment]
Can you send me the sample code?

**Comment by dreampiggy** [comment]
No code actually. Just use the coders and `AnimatedImage`, checkout the demo and readme again.

```swift
// AppDelegate.swift
import UIKit
import SDWebImage
import SDWebImageWebPCoder
import SDWebImagePDFCoder
import SDWebImageSVGCoder

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        // Add WebP support
        SDImageCodersManager.shared.addCoder(SDImageWebPCoder.shared)
        SDImageCodersManager.shared.addCoder(SDImagePDFCoder.shared)
        SDImageCodersManager.shared.addCoder(SDImageSVGCoder.shared)
        return true
    }
// ContentView

var body: some View {
    AnimatedImage(url: "https://raw.githubusercontent.com/icons8/flat-color-icons/master/pdf/stack_of_photos.pdf")
}
```

**Comment by mkalayci35** [comment]
<img width="727" alt="Screen Shot 2019-11-11 at 20 57 27" src="https://user-images.githubusercontent.com/38668796/68609263-e1b49c80-04c5-11ea-8984-5898d2aa8193.png">

**Comment by dreampiggy** [comment]
Specify branch. I already mentioned, use `iOS13_SVG` branch.

**Comment by dreampiggy** [comment]
Or just use CocoaPods. I don't like SwiftUI actually (it's a young toy with compared to other package manager for real-world complicated software develop and dependency).

```
target 'SDWebImageSwiftUIDemo' do
  platform :ios, '13.0'
  pod 'SDWebImageSwiftUI', :path => '../'
  pod 'SDWebImageWebPCoder'
  pod 'SDWebImagePDFCoder'
  pod 'SDWebImageSVGCoder', :git => 'https://github.com/SDWebImage/SDWebImageSVGCoder.git', :branch => 'iOS13_SVG'
end
```

**Comment by mkalayci35** [comment]
SwiftUI is good for me. Increased my coding and design skills. I just started writing. Well, can't you make the Swift Pack compatible? I don't want to upload pods :(

**Comment by dreampiggy** [comment]
> Specify branch. I already mentioned, use `iOS13_SVG` branch.

This is compatible. Use the branch dependency.

I can not merge that into master and release. Because all current user who use that framework, it's desigend to use SVGKit (another SVG parser), and support iOS 8+. I'm a framework author, should not break my user's code.

I'm considered to release a major version bump for SVGCoder (which drop SVGKit support).  But this need extra consideration (such like naming ? How my current user migrate ? How can these two solution be used seamlessly). There're things to considerate.

For now, just use the branch dependency. You can see that Xcode GUI have a nice checkbox to use `Branch` and `Commit` dependency, don't you ? :)

**Comment by mkalayci35** [comment]
Yes, Branch Maybe, I'il take it from there. I try :)

**Comment by mkalayci35** [comment]
oo okay, https://github.com/SDWebImage/SDWebImageSVGCoder/tree/iOS13_SVG  I get it now. :) :D

**Comment by mkalayci35** [comment]
I installed. Thank you very much. I got it late. Sorry :)

**Comment by mkalayci35** [comment]
would you do that branch ıos 13 thank you
<img width="743" alt="Screen Shot 2019-11-11 at 21 29 04" src="https://user-images.githubusercontent.com/38668796/68611065-4a9e1380-04ca-11ea-8081-9ff48670c5d1.png">

**Comment by mkalayci35** [comment]
THANK YOU :) 
<img width="334" alt="Screen Shot 2019-11-11 at 21 57 00" src="https://user-images.githubusercontent.com/38668796/68612709-30fecb00-04ce-11ea-9667-4d2d394a1a27.png">

**Comment by dreampiggy** [comment]
WebP coder does not support SwiftPM. This is because [libwebp](https://github.com/webmproject/libwebp) (The upstream dependency) does not support. Simple answer.

If you want to see all our coder plugins to support SwfitPM, this need time. Previouslly, I need to wait the codec author (Google, for example, the maintainer of libwebp) to support it.

However, if they can not, we have another backup solution, to just fork their repo and provide one support. Though I don't like this, but it's a reasonable solution.

Or we can use our Carthage package repo: https://github.com/SDWebImage/libwebp-Xcode. To add support here.

**Comment by dreampiggy** [comment]
But since SwiftPM is sucked to just use `Git Tag` for version. Which means, since there're already libwebp v1.0.3 version tagged. If I want to support SwiftPM, I need to `Re-tag` that tag, or create a new repo. Only two choices. Both of them arenot a good idea for all of my users. (Break something)

**Comment by dreampiggy** [comment]
@mkalayci35 The [SDWebImageSVGCoder v1.0.0](https://github.com/SDWebImage/SDWebImageSVGCoder/releases/tag/1.0.0) released. We drop the original SVGKit support into another repo.

For you, the `iOS13_SVG` branch is already merged and deleted. You can just using SwiftPM to specify `~> 1.0` version of the SVGCoder for usage.

**Comment by dreampiggy** [comment]
@mkalayci35 Another note:

+ Only `AnimatedImage` supports vector rendering. You can dynamic change to any size without lossing details.

The Animated ImageView will show a `PDF` or `SVG` label if it supports vector rendering.

![image](https://user-images.githubusercontent.com/6919743/68946275-85b38600-07ed-11ea-9b1f-c0d364f5c66f.png)

+ The `WebImage` can use the bitmap rendering, which means we decode SVG/PDF as a bitmap image, but it will looks blur when scaling. You can check our Demo code to see how we do that: [AppDelegate.swift](https://github.com/SDWebImage/SDWebImageSwiftUI/blob/master/Example/SDWebImageSwiftUIDemo/AppDelegate.swift)

**Comment by mrtrinh5293** [comment]
> No code actually. Just use the coders and `AnimatedImage`, checkout the demo and readme again.
> 
> ```swift
> // AppDelegate.swift
> import UIKit
> import SDWebImage
> import SDWebImageWebPCoder
> import SDWebImagePDFCoder
> import SDWebImageSVGCoder
> 
> @UIApplicationMain
> class AppDelegate: UIResponder, UIApplicationDelegate {
>     func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
>         // Override point for customization after application launch.
>         // Add WebP support
>         SDImageCodersManager.shared.addCoder(SDImageWebPCoder.shared)
>         SDImageCodersManager.shared.addCoder(SDImagePDFCoder.shared)
>         SDImageCodersManager.shared.addCoder(SDImageSVGCoder.shared)
>         return true
>     }
> }
> 
> // ContentView.swift
> 
> var body: some View {
>     AnimatedImage(url: "https://raw.githubusercontent.com/icons8/flat-color-icons/master/pdf/stack_of_photos.pdf")
> }
> ```

thank you so much my app really work now Thank you so so much!!

**Comment by netgfx** [comment]
How do you initialize the SVG Coder for a SwiftUI project? It doesn't have an AppDelegate file. Thanks!

**Comment by dreampiggy** [comment]
> How do you initialise the SVG Coder for a SwiftUI project? It doesn't have an AppDelegate file. Thanks!

For pure SwiftUI project, just use `UIApplicationDelegateAdaptor`. See Apple's documentation.
https://developer.apple.com/documentation/swiftui/uiapplicationdelegateadaptor
https://www.hackingwithswift.com/quick-start/swiftui/what-is-the-uiapplicationdelegateadaptor-property-wrapper

**Comment by dreampiggy** [comment]
Or you can just mixed to use AppDelegate and SwiftUI at the same time. SwiftUI is not magic, it still need `UIHostingViewController` for hosting your pure SwiftUI view. It's still here.

**Comment by netgfx** [comment]
![F1E8E893-0A1E-4D81-92F9-46A41D79349B_1_105_c](https://user-images.githubusercontent.com/864248/102880258-b2f05000-4453-11eb-8032-cb3991e6de5c.jpeg)

@dreampiggy I'm getting this error while following the instructions both on your comment and on this thread. Unless I'm missing something on a pure SwiftUI project. Thanks for the links btw!

**Comment by dreampiggy** [comment]
@netgfx Found you're really new to iOS dev.

The UIApplicationDelegate, is a protocol, so, you must implementation the code in a protocol method.

Normally, put this into the https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428385-applicationdidfinishlaunching

Suggestion: You can start learning iOS dev by a full tutorial, not just try something from the part. Like: + 

https://developer.apple.com/documentation/uikit/app_and_environment/managing_your_app_s_life_cycle?language=objc
+ https://peterfriese.dev/ultimate-guide-to-swiftui2-application-lifecycle/
