### ISSUE TITLE
Issue with private API (AnimatedImage)

### ISSUE THREAD

**Issue by tiepvuvan** [SDWebImage/SDWebImageSwiftUI#64]
We're trying to upload binary to AppStoreConnect, but we got this error, seem like we should remove the private API of AnimatedImage
<img width="654" alt="Screen Shot 2019-11-29 at 18 23 46" src="https://user-images.githubusercontent.com/5098186/69866058-9b3cab80-12d5-11ea-9579-eea7dcf4b0a1.png">

**Comment by dreampiggy** [comment]
Sounds reasonable. The only way to resolve this, it's to drop the WatchKit support :(

**Comment by dreampiggy** [comment]
I'm working on #43 and replace this implementation.

The old WatchKit is suck on the animation, which Apple itself use `UIKit `method to build the system App, but you can not.

SwiftUI is the actual **Native UI framework** for watchOS.

**Comment by dreampiggy** [comment]
It's done.

Now, from v0.9.0, if you really want to use Animated Image on watchOS, you should use `WebImage` instead, with the new `public func animated(_ animated: Bool = true) -> WebImage` API

```swift
WebImage(url: URL(string:url))
.resizable()
.animated()
.animation(.easeInOut(duration: 0.5))
.transition(.fade)
.scaledToFit()
```

It's a SwiftUI view (not UIViewRepresentable), without any hack. But currently, because of SwiftUI's layout system and rendering system, the performance may be a little slower than the `SDAnimatedImageView` (our current AnimatedImage UIView implementation).

But this is the best compatible components for SwiftUI. Which use all the SwiftUI lifecycle. After I release the new version, you can have a try with that.

**Comment by dreampiggy** [comment]
@tiepvuvan Use [v0.9.0](https://github.com/SDWebImage/SDWebImageSwiftUI/releases/tag/0.9.0) and new `WebImage` instead.
