### ISSUE TITLE
1.0.0beta2 only available in SwiftPackageManager if ("master") branch rule is used 

### ISSUE THREAD

**Issue by TysonParks** [SDWebImage/SDWebImageSwiftUI#78]
Is this the desired behavior?

I understand that you could be doing this in order to prevent users from accidentally upgrading to the beta instead of the last stable 0.1... release? But according to the updated readme it seems like you want people to be able to use the version rule set to " ...from: "1.0") "

BTW, the updated Readme looks great and I'm excited to test the beta!

**Comment by dreampiggy** [comment]
Seems the Xcode's Swift PM integration (note it's not open-sourced SwiftPM itself), does not support you to add a specify version, or using the pre-release version ?


If you're a framework author, who want to add dependency of a beta version package like us, you should write Package.swift like this:

```swift
let package = Package(
    dependencies: [
        .package(url: "https://github.com/SDWebImage/SDWebImageSwiftUI.git", from: Version(1, 0, 0, prereleaseIdentifiers: ["-beta2"])))
    ],
)
```

See more on documentation: https://developer.apple.com/documentation/swift_packages/version/2878264-prereleaseidentifiers

If you're the end-application integrator, who want to use the specify version of a beta version package, you should use Xcode's version dependency, with the `Range` one, or the `Exact` one to match the pre-release version. See [Xcode's documentation](https://developer.apple.com/documentation/xcode/adding_package_dependencies_to_your_app?language=objc) for this...Should I mention this on readme ? Because I think teaching how to use SwiftPM seems not related to a framework itself

![image](https://user-images.githubusercontent.com/6919743/73805686-5451c180-4802-11ea-9b72-d082ad315bfc.png)

**Comment by dreampiggy** [comment]
The 1.0.0 release version will be available soon... (If there are no huge bug, or features which cause API break during user's testing)

**Comment by TysonParks** [comment]
Thanks for your quick replies!

Okay, yes I see, so it appears to be SwiftPM's limitation!? That makes sense as it prevents someone from accidentally updating to a beta version. 

I'm currently testing by utilizing the ' Branch: "master" ' rule which is fine for me and was easy enough to figure out. But I'd guess with SwiftPM so newly integrated into Xcode that many devs are relatively new to SwiftPM?

So I agree it's probably worth adding a small note either in the "Version" or "Installation" section of the ReadMe to let people know how to test via SwiftPM... just to maximize beta usage/feedback.

**Comment by dreampiggy** [comment]
@TysonParks I've update the Readme which describe the toturial for both Framework author and App integration for SwiftPM. You can have a check as well:
https://github.com/SDWebImage/SDWebImageSwiftUI#swift-package-manager

**Comment by TysonParks** [comment]
Looks great! Thanks!
