### ISSUE TITLE
Using backward deployment on iOS 12.1 will crash, iOS 12.2+ works fine

### ISSUE THREAD

**Issue by djr** [SDWebImage/SDWebImageSwiftUI#80]
Hello,

Thank you for bringing support for iOS 12.  When testing on iOS 12.4 we have no issues.  Testing on iOS 12.1 causes this crash:

dyld: Library not loaded: /usr/lib/swift/libswiftCore.dylib
  Referenced from: /Users/djrossi/Library/Developer/CoreSimulator/Devices/5D46194E-556D-477F-96BC-E3BDE9687113/data/Containers/Bundle/Application/A2C4C78B-6135-4409-92CF-D6D7CECEF853/Charge.app/Frameworks/SDWebImageSwiftUI.framework/SDWebImageSwiftUI
  Reason: no suitable image found.

I tested using the iOS 12.1 simulator and 1.0.0-beta2.  Thank you for the help.

**Comment by dreampiggy** [comment]
Carthage ?


Seems the issue caused by the Swift when using Carthage and turn on Library Evolution ?

Swift have a smart check, when the min deployment target version is iOS 13.0+, it link the system framework.

When iOS 12.4-(which does not have Swift built in), it use the embed Swift dynamic framework.

If you want to deploy both iOS 12 && iOS 13, maybe the final ipa produce must keep the Swift dynamic framework. This can not been workaround without chaning the min deployment target version.

Could you please, using Carthage to pull the project with `--no-build`, changing the min deployment target version to iOS 12, and build it manaual to add ?

**Comment by dreampiggy** [comment]
What I've done is that `I don't want to change the min deployment target version for this Package`.

Because changing min deployment target, will have a bad effect on user, who only build their App for iOS 13+. It will cause performance dropdown and ipa size become bigger.

**Comment by dreampiggy** [comment]
I'll try to find other solution. The worst idea is to change the min deployment target version to iOS 12, or totally remove the min deployment target version.

**Comment by dreampiggy** [comment]
Can this `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` works for this case ? Turn this on to bundle the Swift runtime framework.

I remember when Submitting to App Store, App Store will strip the Swift Runtime when the end-user use iOS 12.4+.

**Comment by dreampiggy** [comment]
I think the final solution is to set the min deployment target version.

But I will not done this here, because as a framework author, I don't want to `Decrease my most users' (who use iOS 13+ only) performance because of that I want to backward support on iOS 12).

You can choose:

1. Set your minimum deployment target version to iOS 12.2, this is when the Swift runmtime built-in
2. If you still want to support user who use iOS 12.1 or lower, you can use Carthage to download the project, then change the minimum deployment target to what you want, such as iOS 8, then build and link it to your App project.

See more: https://forums.swift.org/t/does-swift-5-runtime-support-swift-4-2/23240

**Comment by djr** [comment]
Thanks @dreampiggy!  Rather than setting up Carthage, I'd like to try forking the repository and changing the deployment target.  This is just for testing purposes.  I changed the deployment target to iOS 12.0 in the project and the target settings, but I'm still having the same crash.  Am I missing something?  I also changed it in the podspec to be safe.

**Comment by dreampiggy** [comment]
I think this is the idea. It's not so hard for most cases.

+ Carthage: use `carthage update --no-build`, change the Xcodeproject's min deployment target and click `Archive` to produce binary
+ CocoaPods: use Podfile's `post_installer` to modify the Pod's min deployment target version, those can works for all the pods once, better thatn Carthage which you need to edit once again

**Comment by fermoya** [comment]
Hi, I found a similar issue in my framework. Recently, a user asked me to enable compatibility with iOS 12 and lower. I also refused to change the deployment target and was looking for another solutions. I've been using this thread as a reference.

What I've managed to do is the following:
- I add the same `@available` wrappers to make it explicit it only works with iOS 13+
- In the project file I use to build Carthage frameworks, I've added a non-shared aggregate target and use it to generate a _xcframework_.
- I've made every shared target here _weak_link_ both `SwiftUI` and `libswiftCore`
<img width="811" alt="Screenshot 2020-06-07 at 18 47 08" src="https://user-images.githubusercontent.com/11335612/83976040-554d4980-a8ef-11ea-963a-e79125311a61.png">

So now, I'm able to use the _xcframework_ on any platform version. No compiler error when importing the module and no issue when running.

I haven't been able to make it work with Cocoapods or SPM

**Comment by dreampiggy** [comment]
> I've made every shared target here weak_link both SwiftUI and libswiftCore

You miss the `Combine` framework, which is imported by SwiftUI and iOS 13 only as well. However, pre to Xcode 11.4, there is a bug you can not use GUI to set the weak framework. You can use `-weak_framework Combine` the linker flags to do the same thing.

**Comment by dreampiggy** [comment]
Will not solve.

I will drop the iOS 13 support in the future. It's pain to maintain backward compatibility for SwiftUI. Because Apple does not provide any good workaround and changes behavior from version to version.
