### ISSUE TITLE
EXC_BAD_ACCESS crash on some SVGs using AnimatedImage

### ISSUE THREAD

**Issue by teepsdonnelly** [SDWebImage/SDWebImageSwiftUI#87]
In a SwiftUI view:

`  AnimatedImage(url: URL(string: self.imageUrlString))
.resizable()
.scaledToFit()
.frame(width: self.width, height: self.height, alignment: .center)`

Some SVGs cause EXC_BAD_ACCESS crash, but I'm having a hard time identifying which one specifically due to the async nature and not being sure which images are finishing loading first.

As far as I can tell, it's one of these 3 SVGs causing the crash but I don't know what's wrong with them:

```
https://static.hltv.org/images/team/logo/4863
https://static.hltv.org/images/team/logo/10386
https://static.hltv.org/images/team/logo/4602
```

![Screen Shot 2020-03-27 at 9 36 16 AM](https://user-images.githubusercontent.com/824322/77761604-af3bb400-700e-11ea-8406-66ffc4b42549.png)

![Screen Shot 2020-03-27 at 9 36 34 AM](https://user-images.githubusercontent.com/824322/77761615-b2cf3b00-700e-11ea-827b-a43bb06126e6.png)

**Comment by dreampiggy** [comment]
I’ll check this issue tomorrow.

Any extra code in your usage of AnimatedImage ?
For example, did you use AnimatedImage View inside a NavigationLink ?

Be sure to use. buttonStyle to default or many strange issue will happen. See the common mistake part of our readme

**Comment by dreampiggy** [comment]
Seems this is because your SVG file contains something Apple's SVG parser can not correctly render. 

Check https://developer.apple.com/documentation/xcode/creating_custom_symbol_images_for_your_app, convert it firstly to make sure it can render on the Symbol App on Mac, then retry with the new SVG one.

Apple's iOS 13 CoreSVG.framework does not provide full SVG/1.1 support, which actually seems only support [SVG-native](https://w3c.github.io/svgwg/specs/svg-native/index.html) W3C standard.

**Comment by dreampiggy** [comment]
I guess from the stacktrace, maybe this cause issue:

```
<style type="text/css">
	.st0{fill:#161616;}
	.st1{fill:#A3242E;}
	.st2{fill:#D63831;}
	.st3{fill:#FFFFFF;}
	.st4{fill:#C8C8C8;}
</style>
```

Could you try to use the inline color fill, like `<path class="st0" d="M399.8,68.2c77.3,3.1,160.6", fill="#abcdef"/>` instead ?

**Comment by dreampiggy** [comment]
I test that remove the `<style type="text/css">` totally works...But need to fill the path with color :(

![image](https://user-images.githubusercontent.com/6919743/77814619-93f3a600-70ed-11ea-832a-9268612f0746.png)

**Comment by dreampiggy** [comment]
Test write color with CSS name works, maybe the issue is the HEX expression:

![image](https://user-images.githubusercontent.com/6919743/77814643-d74e1480-70ed-11ea-8c9f-0fb06fbb8b1e.png)

![image](https://user-images.githubusercontent.com/6919743/77814644-d917d800-70ed-11ea-985d-e9dd67e145c8.png)

**Comment by dreampiggy** [comment]
Test using the `rgb` syntax instead of HEX expression, works :)

So you must change all the HEX color into RGB syntax, or Apple's CoreSVG framework can not parse it correctly

![image](https://user-images.githubusercontent.com/6919743/77814673-49265e00-70ee-11ea-9f70-b059f2ec41fc.png)


![image](https://user-images.githubusercontent.com/6919743/77814670-40ce2300-70ee-11ea-9afb-277ef291092d.png)

**Comment by dreampiggy** [comment]
After another check, I found the issue does not comes from your first two SVG files...Which cause the misunderstanding.

The issue is the third one: https://static.hltv.org/images/team/logo/4602

Which use the CSS `opacity` for `path` element:

```
	.st0{fill:#9D1C31;}
	.st1{fill:#CB1436;}
	.st2{fill:#1D243C;}
	.st3{fill:#C5C2C3;}
	.st4{fill:#FFFFFF;}
	.st5{fill:none;}
	.st6{fill-opacity:0.15;fill:#1D243C;}
</style>
```

You should replace the `opacity:0.15` into the `fill-opacity:0.15`, or use `rgab` in color like `file`, the opacity seems cause issue for CoreSVG.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/77822530-9aeed880-712e-11ea-8545-691d57617db1.png)

**Comment by dreampiggy** [comment]
@@teepsdonnelly Close this  ?

**Comment by teepsdonnelly** [comment]
Ah thanks for looking into this so quickly @dreampiggy -- This is a resource I don't have access to change if that makes sense. Basically, I'm consuming this from a third-party API that is wrapping a website, and that third party API is passing back URLs for logos for eSports teams.

Currently, it seems like this is all a result of a bug in Apple's SVG parser as you mentioned. Is this something I should file with them or are there any other workarounds you can think of that don't involve modifying the SVG?

**Comment by dreampiggy** [comment]
You’d better host a mirror or proxy for that SVG files. This crash happened inside low-level API, no good thing to workaround.

If you really really don’t have any own Image Host Server, you can hack from client side...

Use SDWebImage’s Data Decrypter API (which give you origin URL and Data, you return the modified one), check that SVG url and provided the modified version from your App bundle or some where. Sounds super hack but works...

See: https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#data-decryptor-530

**Comment by dreampiggy** [comment]
```swift
static var svgDecryptor = SDWebImageDownloaderDecryptor { (data, response) -> Data? in
    if let url = response?.url, url.absoluteString == "https://static.hltv.org/images/team/logo/4602" {
        let localSVGPath = "xxx"
        return try? Data(contentsOf: URL(fileURLWithPath: localSVGPath))
    } else {
        return data
    }
}
AnimatedImage(url: url, options: [], context: [.downloadDecryptor : svgDecryptor])
```

**Comment by teepsdonnelly** [comment]
Wow! Honestly I had no idea about the Data Decryptor API, thanks so much for helping -- you're amazing.

I tried your code suggestion and it seems to be working. I think we can close this one out for now since it definitely doesn't appear to be an issue on SDWebImage's side.
